engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - client/**/*
  - server/**/*
  - shared/**/*
exclude_paths:
- shared/**/*.spec.js
- shared/regex/symbols/pegjs/*.js
