os:
  - linux
language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
after_script:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache: yarn
